version: '3'
services:
  app:
    build:
      context: .
    # apply to local change
    volumes:
      - ./src:/src
      - ./tests:/src/tests
    ports:
      - "5042:5042"
    environment:
      DEBUG: "true"