version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5-stretch
    steps:
      - checkout
      - run:
          name: install pipenv
          command: sudo pip install pipenv
      - run:
          name: install dependencies and run flake8
          command: |
           cd ./src
           pipenv install
           pipenv run flake8 --max-line-length=300 --ignore=F401, F821
      - run:
          name: run pytest
          command: |
           pipenv run pytest